name: Hello

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: 'Reewright'